olucurious/PyFCM

README.rst
The git protocol is insecure -- no server validation whatsoever is performed. Doing `pip install git+git://...` without an `@<commit_hash>` can compromise a user's machine if an attacker is able to intercept their connection (trivial on unsecured or shared-password WiFi, for example).
This change directs users to do the safer thing instead.
=> Update README.rst to direct users to use https:// instead of insecure git://

pyfcm/__meta__.py
Currently the latest release tag has version number 0.0.9, but __meta__.py has version 0.0.7. This results in the confusing situation where a user does `pip install git+git://github.com/olucurious/PyFCM.git` and then `pip freeze` reports `pyfcm==0.0.7`.
While it's too late to fix `0.0.8` or `0.0.9`, it is possible to fix it for `0.0.10` onwards.
=> Bump version number to 0.0.10

CHANGES.rst, pyfcm/baseapi.py
Add support for extra_kwargs in notify_single_device/notify_multiple_devices functions
It may be necessary for cases where the payload is constructed dynamically and no possibility to define each function parameter
=> support for extra_kwargs in notify_single_device/notify_multiple_devices functions

pyfcm/baseapi.py
success is not a boolean: as a result, the removed lines could produce an incorrect result (success = 1) in the case that multiple messages were sent. Regardless, success was already set accurately on line 63. See here for more info: https://developers.google.com/cloud-messaging/http-server-ref
=> Remove extraneous assignment of 1 to success

pyfcm/fcm.py
Issue #77 
A quick look revealed that only a return statement was missing in function notify_single_device. 
I think you can release version 1.1.1 with this fix.
I will try to write some unit tests as soon as possible.
=> None response hotfix

README.rst
I think app_engine is supposed to be a string in this context.
=> Add missing README quote

README.rst, pyfcm/baseapi.py, pyfcm/fcm.py
Currently we're sending the notification object regardless.  This sends a notification rather than a data message as described here: [https://firebase.google.com/docs/cloud-messaging/concept-options
](https://firebase.google.com/docs/cloud-messaging/concept-options
)
I've added a remove_notification flag which is set to True in the message_single_device/message_multiple_devices functions, which I also created.  This just removes the notification object in the requests sent to FCM.  The new message functions are essentially just copies of the notify functions with the notification arguments removed and the remove_notification argument set to True.
I'm open to implementing this in a different way if needed.  I played with the idea of a basic parse_payload function that does the things …
=> Add the abilty to send only a data message.

CHANGES.rst, pyfcm/baseapi.py
This allows custom encoding of objects to JSON
https://docs.python.org/3/library/json.html#json.JSONEncoder
The encoder class is passed to `json.dumps` call throughthe `cls` argument
This allows configuring the JSONEncoder to be different by the default one and for example transform `datetime` values to its `isoformat`
I use this with the rest_framework encoder in my project like in this example:
```
from pyfcm import FCMNotification
from rest_framework.utils.encoders import JSONEncoder
from datetime import datetime
push_service = FCMNotification(api_key="<api-key>", json_encoder=JSONEncoder)
result = push_service.single_device_data_message(
registration_id="<registration_id>", 
data_message={'timestamp': datetime.now()})
```
=>  Add optional json_encoder argument to BaseAPI constructor

CHANGES.rst, pyfcm/baseapi.py
with reference to https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message the payload sent with the dict ` 'android': {'priority': 'high'}` for data messages is working as expected than sending as `'priority': 'high'` in the payload, test devices used for this are Xiaomi and One Plus different models, using android the notification is delivered even when the app is idle whereas in the other case the notification is not delivered. Tested the issue with time_to_live=0 for highest latency and without android as the outer dict, was unable to get the message. Reproducible by using the above devices with battery optimization on for a certain application. I have forked your repo and using it in a production environment with android dict with success. If …
=> Fcm priority

README.rst
These extra 0xC2s cause installation under Python 3 to fail with this error:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "setup.py", line 41, in <module>
long_description=read('README.rst'),
File "setup.py", line 17, in read
return open(os.path.join(os.path.dirname(__file__), fname)).read()
File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4184: ordinal not in range(128)
=> Remove extra 0xC2 bytes from README.rst.

pyfcm/baseapi.py
This pull request adds two methods to `FCMNotification` to manage subscriptions to topics. 
```python
service = FCMNotification(SERVER_KEY)
tokens = [
<registration_id_1>,
<registration_id_2>,
]
subscribed = service.subscribe_registration_ids_to_topic(tokens, 'test')
unsubscribed = service.unsubscribe_registration_ids_from_topic(tokens, 'test')
```
Apologies if this is redundant, but I couldn't find it anywhere else in the code. Also: Apologies if the error handling is not exactly up to snuff, or to the style of the project.
=> Adds topic subscription management.

CHANGES.rst, pyfcm/__meta__.py, pyfcm/baseapi.py, pyfcm/fcm.py
Starting in Android 8.0 (API level 26), all notifications must be assigned to a channel or it will not appear.
I added the parameter 'android_channel_id' to methods that send a push notification.
[Android Developer Reference](https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels)
=> Add android_channel_id

pyfcm/baseapi.py
Resolves #206 
Reverts the changes made in #171 to fix broken high priority messages.
=> Revert to legacy FCM API priority

LICENSE, README.rst
I put the MIT license of the project in a new file called `LICENSE`. This is the recommended way to add a license. For users, it is clearer as well, because using a `LICENSE` file is the conventional way to do it.
I also updated the copyright year of the license.
=> Put license in LICENSE file and update year

CHANGES.rst, pyfcm/__meta__.py, pyfcm/baseapi.py
We've started getting a lot of `ConnectionErrors` which break the loop of `clean_registration_ids`. This adds configurable retries to alleviate this.
=>  Add configurable retries to info endpoint

pyfcm/fcm.py
Data messages currently being allowed only for "single device" or "multiple devices" using their registration IDs. An obvious extension of that would be to allow data messages to topics.
Sending the pull request to develop branch instead of master.
=> added "topic_subscribers_data_message" method

CHANGES.rst, pyfcm/baseapi.py, tests/test_baseapi.py
According to the firebase documentation 0 is a valid value for `time_to_live`. This fixes the check so that we can send that value along.
> Another advantage of specifying the lifespan of a message is that FCM never throttles messages with a time-to-live value of 0 seconds. In other words, FCM guarantees best effort for messages that must be delivered "now or never." Keep in mind that a time_to_live value of 0 means messages that can't be delivered immediately are discarded. However, because such messages are never stored, this provides the best latency for sending notification messages.
=> Fix time_to_live check so that 0 is valid.

pyfcm/async_fcm.py, pyfcm/baseapi.py, pyfcm/fcm.py, requirements.txt, tests/test_fcm.py
For purpose : try to pyfcm asynchronously and send personalized messages
The parameters are the same as notify_multiple_devices except **the parameters are list which contains multiple parameters**
You can send the messages in personalized format
=> [#261] make work PyFCM asynchronously

CHANGES.rst, pyfcm/baseapi.py
Starting on [`v1.26.0`](https://github.com/urllib3/urllib3/releases/tag/1.26.0), urllib3 has deprecated `Retry(method_whitelist=...)` and `Retry.DEFAULT_METHOD_WHITELIST`.
> Deprecated Retry options Retry.DEFAULT_METHOD_WHITELIST, Retry.DEFAULT_REDIRECT_HEADERS_BLACKLIST
and Retry(method_whitelist=...) in favor of Retry.DEFAULT_ALLOWED_METHODS,
Retry.DEFAULT_REMOVE_HEADERS_ON_REDIRECT, and Retry(allowed_methods=...)
(Pull #2000) Starting in urllib3 v2.0: Deprecated options will be removed
=> Replace deprecated urllib3.Retry options

setup.py
Adds `urllib3>=1.26.0` to list of installation requirements.
This should fix issues like #282.
=> urllib3 install dependency

pyfcm/async_fcm.py, pyfcm/fcm.py
Type hints are excluded for python 2.7 compatibility, but they remain in two places, causing an error.
https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L564
https://github.com/olucurious/PyFCM/blob/master/pyfcm/async_fcm.py#L5
issue https://github.com/olucurious/PyFCM/issues/295
=> Remove annotaions for python 2.7

PyFCM.iml, pyfcm/baseapi.py
Per psf/requests/issues/2766 requests.Session is likely not threadsafe.
This change puts the session in a thread local so that each thread has a different copy.
=> Ensure requests.Session is not shared between threads

.github/workflows/python-app.yml, pyfcm/v1/baseapi.py, pyfcm/v1/fcm.py, requirements.txt, tests/test_v1_baseapi.py
Added v1 endpoints for pyFCm in new v1 package.
Added test for v1 baseapi
=> Added v1 endpoints for pyFCm in new v1 package.

.github/workflows/python-app.yml
- Added black formatting steps to check whether the codes are formatted or not before merge
- Fixed pipeline - should run on every action for code quality checks
=> - Fixed pipeline - should run on every action for code quality checks

pyfcm/baseapi.py, pyfcm/fcm.py
=> - Formatted code

pyfcm/baseapi.py
The following TypeError occurred when a 401 error occurred. 
Fixed to use AuthenticationError.
```
Traceback (most recent call last):
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/pyfcm/fcm.py", line 67, in notify
return self.parse_response(response)
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/pyfcm/baseapi.py", line 195, in parse_response
raise ("There was an error authenticating the sender account")
TypeError: exceptions must derive from BaseException
```
=> raise AuthenticationError when status_code == 401

pyfcm/baseapi.py
fix: #334.
Supported access token refresh when it expires.
According to the [official documentation](https://cloud.google.com/apigee/docs/api-platform/antipatterns/oauth-long-expiration), access tokens expire in 30 minutes.
```
$ export GOOGLE_APPLICATION_CREDENTIALS="service_account.json"
$ export FCM_TEST_PROJECT_ID=test
$ python -m pytest
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /Users/***/Desktop/PyFCM
plugins: mock-3.14.0
collected 4 items …
```
=> fix: refresh access token

README.md, pyfcm/baseapi.py, tests/test_fcm.py
Users may want to use prepared credentials for security reason (e.g., to avoid creating private keys for service accounts).
=> Feature: Supports credentials injection

pyfcm/baseapi.py, setup.py
these fixes make things work in  our  Python 3.6.9 env
=> enable Python 3.6.9

CHANGES.rst, pyfcm/baseapi.py, pyfcm/errors.py, pyfcm/fcm.py
Small additional check to separate 403s from generic `FCMServerError`. Also updates the `notify` docstring in line with the changes to `parse_response` in 2.x
=> Explicitly handle SENDER_ID_MISMATCH 403 error response

pyfcm/baseapi.py, tests/test_baseapi.py
Related: #334
Implements automatic access token refresh functionality when tokens expire during FCM API requests.
When 401 error responses with reason:ACCESS_TOKEN_EXPIRED, retry another request.
```bash
python -m pytest
======================================== test session starts ========================================
platform darwin -- Python 3.12.10, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/niccari/Desktop/PyFCM
plugins: mock-3.14.1
collected 8 items                                                                                   
tests/test_baseapi.py .....                                                                   [ 62%]
tests/test_fcm.py ...                                                                         [100%]
========================================= 8 passed …
```
=> feat: refresh access token when expired

pyfcm/baseapi.py, pyfcm/fcm.py, tests/conftest.py, tests/test_baseapi.py, tests/test_fcm.py
Fixed an issue pointed out by flake8 warnings/errors where workflows would fail on Github Actions as shown in #366 .
=> Fix: applied code formatting (flake8, black)

CONTRIBUTING.rst, pyfcm/baseapi.py, tests/conftest.py, tests/test_baseapi.py, tests/test_fcm.py
fixes unit test issue at https://github.com/olucurious/PyFCM/actions/runs/16545059983/job/46791440559
This PR defers credentials loads until it needed, unit tests now run without requiring credentials setting.
=> feat: lazy load service-account private key until it needed - unit test does not requires credentials setting

requirements.txt
This PR fixes requirements.txt conflict between urllib3 and google-auth in the master branch.
- Updated google-auth to 2.24.0, compatible with urllib3 > 2 and python 3.12.
- Updated urllib3 to 2.5.0, same version as main branch (https://github.com/olucurious/PyFCM/commit/6b9205e51cc37a71787736561bd774a93eb37bc4).
```bash
=================================================================== test session starts ====================================================================
platform darwin -- Python 3.10.18, pytest-8.4.1, pluggy-1.6.0
plugins: mock-3.14.1
collected 8 items                                                                                                                                          
tests/test_baseapi.py ..... …
```
=> fix: requirements.txt, match master's urllib3 version (2.5.0)
